Update test.yml fixing port

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,23 +54,23 @@ jobs:
       - name: Start Server
         run: npm start &
         env:
-          PORT: 7001
-          TEST_BASE_URL: "http://localhost:7000"  # Point to local CI server
-          LOGIN_TOKEN : ${{ secrets.LOGIN_TOKEN }}
-          TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
-          MONGO_URL: ${{ secrets.MONGO_URL }}
-
-      - name: Wait for server
-        run: sleep 5
-
-      - name: Run Tests
-        run: npm test  # Ensure tests include DB cleanup
-        env:
-          PORT: 7001
+          PORT: 7000
           TEST_BASE_URL: "http://localhost:7000"  # Point to local CI server
           LOGIN_TOKEN : ${{ secrets.LOGIN_TOKEN }}
           TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
           MONGO_URL: ${{ secrets.MONGO_URL }}
 
       - name: Stop Server
-        run: kill $(lsof -t -i:7001) || echo "No process to kill"
+        run: kill $(lsof -t -i:7000) || echo "No process to kill"
+
+      - name: Run Tests
+        run: npm test  # Ensure tests include DB cleanup
+        env:
+          PORT: 7000
+          TEST_BASE_URL: "http://localhost:7000"  # Point to local CI server
+          LOGIN_TOKEN : ${{ secrets.LOGIN_TOKEN }}
+          TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
+          MONGO_URL: ${{ secrets.MONGO_URL }}
+
+      - name: Stop Server
+        run: kill $(lsof -t -i:7000) || echo "No process to kill"
